H3
denisa2341/Prak pull request #7
Opened 2019-10-23 19:01 UTC by denisa2341

Тумояков(308)

2019-10-26 17:01 UTC, illarionovEA requested changes
confusion matrix не увидел

откуда эти числа, почему вбиты руками
```python
k = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
x = np.array(k)
y = np.array([0.8,0.8,0.8,0.8,0.6,0.6,0.6,0.6,0.6,0.4,0.4,0.4,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2])
```

сделан вывод, что сильно путаются ... - на чем основан этот вывод, где подтверждение графиками, числами, таблицей?

много дублирующего кода, от него нужно избавиться
некоторые ячейки не запущены

2019-11-04 17:00 UTC, illarionovEA commented
ноутбук с ошибками
потерялись картинки

2019-12-24 11:41 UTC, denisa2341 commented
исправил ошибки
Вот ссылка на профиль с необходимым уровнем (сразу для 4 задач)
https://www.codewars.com/users/denisa2341

2019-12-25 10:44 UTC, illarionovEA approved these changes

2019-12-26 16:07 UTC, merged